# Generated by Django 5.0.4 on 2024-05-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('genus_name', models.CharField(max_length=100)),
                ('specie_name', models.CharField(max_length=100)),
                ('orchard', models.IntegerField()),
                ('maize', models.IntegerField()),
                ('rice', models.IntegerField()),
                ('rubber', models.IntegerField()),
                ('teak', models.IntegerField()),
                ('bambou', models.IntegerField()),
                ('fallow', models.IntegerField()),
                ('community_forest', models.IntegerField()),
                ('secondary_forest', models.IntegerField()),
                ('occurence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='plant_pictures')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='Quiz.plant')),
            ],
        ),
    ]
