# Generated by Django 5.0.4 on 2024-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='family_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
