# Generated by Django 5.0.4 on 2024-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_picture_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='number_of_guess',
            field=models.IntegerField(default=0),
        ),
    ]
