# Generated by Django 5.0.4 on 2024-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_plant_number_of_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='plant_pictures/'),
        ),
    ]
